[package]
authors = ["Josh Holmer <jholmer.in@gmail.com>"]
description = "An entropy-based password strength estimator, originally for Javascript by Dropbox."
documentation = "https://docs.rs/zxcvbn"
homepage = "https://github.com/shssoichiro/zxcvbn-rs"
license = "MIT"
name = "zxcvbn"
repository = "https://github.com/shssoichiro/zxcvbn-rs"
version = "1.0.1"

[badges]
travis-ci = { repository = "shssoichiro/zxcvbn-rs", branch = "master" }
maintenance = { status = "passively-maintained" }

[dependencies]
derive_builder = "0.5.0"
fancy-regex = "0.1.0"
itertools = "0.7.0"
lazy_static = "1.0.0"
quick-error = "1.2.0"
regex = "1.0.0"

[dependencies.clippy]
optional = true
version = ">=0.0.100"

[dependencies.serde]
optional = true
version = "1.0.0"

[dependencies.serde_derive]
optional = true
version = "1.0.0"

[dependencies.time]
optional = true
version = "0.1.35"

[dev-dependencies]
quickcheck = "0.6.0"
serde_json = "1.0.21"

[features]
default = ["time"]
dev = ["clippy", "unstable"]
ser = ["serde", "serde_derive"]
unstable = ["lazy_static/nightly"]

[profile.test]
opt-level = 2
